services:
  backend:
    build:
      context: .
      dockerfile: backend/app/Dockerfile
    container_name: ai_support_chatbot_backend
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_ENVIRONMENT=${PINECONE_ENVIRONMENT}

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: ai_support_chatbot_frontend
    ports:
      - "8501:8501"
    volumes:
      - ./uploads:/uploads
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend